import type { Metadata } from 'next';
import { Barlow, Fira_Sans } from 'next/font/google';

import { config as faConfig } from '@fortawesome/fontawesome-svg-core';

import '@fortawesome/fontawesome-svg-core/styles.css';
import './globals.scss';
import './layout.scss';

import Link from 'next/link';
import Image from 'next/image';

import Container from '@/components/Container';
import Header from '@/components/Header';
import Navigation from '@/components/Navigation';
import NavToggleIcon from '@/components/NavToggleIcon';

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['700'],
  display: 'swap',
  variable: '--font-barlow',
});

const fira = Fira_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  display: 'swap',
  variable: '--font-fira',
});

faConfig.autoAddCss = false;

export const metadata: Metadata = {
  title: '2Digits Development Agency',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`h-full flex min-h-full flex-col ${barlow.variable} ${fira.variable} bg-gradient-radial from-[#020365] to-[#01041F]`}>
        <NavToggleIcon />

        <header className="py-6 sm:hidden">
          <Container>
            <Link href="/">
              <Image src="/logo-tagline.svg" alt="2Digits Digital Agency" className="h-8 w-auto" width={208} height={32} />
            </Link>
          </Container>
        </header>

        <Header />

        {children}

        <footer>
          <Container className="flex gap-12 py-8 pb-24 text-xs text-white sm:pb-8">
            <Navigation
              slug="footer"
              className="w-full justify-between gap-4 sm:justify-start sm:gap-8"
            />
          </Container>
        </footer>
      </body>
    </html>
  );
}
